name: CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    env:
      VITE_SERVER_BASE_URL: http://127.0.0.1:3000
      VITE_SERVICES_BASE_URL: http://127.0.0.1:8080

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test
      - name:

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: Development
      url: https://app-overcome.onrender.com
    steps:
      - name: Render deployment
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"
