name: Deployment

on:
  push:
    branches: [ "deploy" ]
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: 
      name: production
      url: https://app-overcome.onrender.com
    steps:
      - name: deploy
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"
